import pandas as pd
import matplotlib.pyplot as plt

# The pristine file generated by your scrubber script
input_file = 'bionexus_clean.csv'

try:
    print(f"Loading data from {input_file}...")
    
    # Read the CSV. 'skipinitialspace=True' prevents errors from spaces after commas
    df = pd.read_csv(input_file, skipinitialspace=True)
    
    # Convert Timestamp from milliseconds to seconds for a cleaner X-axis
    df['Time_s'] = df['Timestamp_ms'] / 1000.0
    
    # Create a figure with 2 vertically stacked subplots that share the X-axis
    fig, (ax1, ax2) = plt.subplots(nrows=2, ncols=1, figsize=(10, 8), sharex=True)
    
    # ==========================================
    # PLOT 1: The BioNexus Telemetry Payload
    # ==========================================
    ax1.plot(df['Time_s'], df['Simulated_Data'], color='tab:blue', linewidth=2)
    ax1.set_title('BioNexus Payload: Simulated Telemetry', fontsize=14, fontweight='bold')
    ax1.set_ylabel('Amplitude', fontsize=12)
    ax1.grid(True, linestyle='--', alpha=0.7)
    
    # ==========================================
    # PLOT 2: UWB Distance Measurement
    # ==========================================
    ax2.plot(df['Time_s'], df['Distance_m'], color='tab:orange', linewidth=2)
    ax2.set_title('UWB Time-of-Flight Ranging', fontsize=14, fontweight='bold')
    ax2.set_ylabel('Distance (Meters)', fontsize=12)
    ax2.set_xlabel('Time (Seconds)', fontsize=12)
    ax2.grid(True, linestyle='--', alpha=0.7)
    
    # Prevent the labels from overlapping
    plt.tight_layout()
    
    # Render the dashboard!
    print("Launching plot dashboard...")
    plt.show()

except FileNotFoundError:
    print(f"Error: Could not find '{input_file}'. Did you run the scrubber script first?")
except KeyError as e:
    print(f"Error: Could not find column {e}. Check the exact column names in your CSV.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")