import pandas as pd
import matplotlib.pyplot as plt

# The file generated by your header-aware scrubber
input_file = 'bionexus_clean.csv'

try:
    # Load data and handle potential spacing issues from the CSV print
    df = pd.read_csv(input_file, skipinitialspace=True)
    
    # Convert Timestamp to seconds for the X-axis
    df['Time_s'] = df['Timestamp_ms'] / 1000.0

    # Create 2 stacked subplots
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 10), sharex=True)

    # ----------------------------------------------------
    # PLOT 1: 3-Axis Accelerometer Data
    # ----------------------------------------------------
    ax1.plot(df['Time_s'], df['Accel_X'], label='X-Axis', color='red', alpha=0.8)
    ax1.plot(df['Time_s'], df['Accel_Y'], label='Y-Axis', color='green', alpha=0.8)
    ax1.plot(df['Time_s'], df['Accel_Z'], label='Z-Axis', color='blue', alpha=0.8)
    
    ax1.set_title('BioNexus Spoke: 3-Axis Acceleration', fontsize=14, fontweight='bold')
    ax1.set_ylabel('Acceleration (mg)', fontsize=12)
    ax1.legend(loc='upper right')
    ax1.grid(True, linestyle='--', alpha=0.6)
    # Add a reference line at 0
    ax1.axhline(0, color='black', linewidth=1, alpha=0.5)

    # ----------------------------------------------------
    # PLOT 2: UWB Distance
    # ----------------------------------------------------
    ax2.plot(df['Time_s'], df['Distance_m'], label='ToF Distance', color='orange', linewidth=2)
    
    ax2.set_title('UWB Time-of-Flight Ranging', fontsize=14, fontweight='bold')
    ax2.set_ylabel('Distance (Meters)', fontsize=12)
    ax2.set_xlabel('Time (Seconds)', fontsize=12)
    ax2.grid(True, linestyle='--', alpha=0.6)

    plt.tight_layout()
    print("Dashboard generated. View your motion profile now.")
    plt.show()

except Exception as e:
    print(f"Error generating plot: {e}")